id: P010768
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD90126
  title: རྔ་བ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    50a06b74e7dc4f0992e284e30b4258a7:
      image_group_id: I1PD90147
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
